config/routes.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'strategies#index'
  resources :strategies, only: %i[index show]
  resources :markets, only: %i[index show]
  resources :balances, only: %i[index]
  resources :strategy_settings, only: %i[update] do
    member do
      post :start
    end
  end
  resources :upstream_markets, only: %i[index show]
  resources :upstreams, only: %i[index show]
  resources :accounts, only: %i[index show]
  resources :drainers, only: %i[index show]
  resources :trades, only: %i[index show]
  resources :buyout_orders, only: %i[index show]
end

app/models/buyout_order.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

# Buyout order
#
class BuyoutOrder < ApplicationRecord
  include SideInquirer

  enum status: %i[initial posted waited ignored done errored]

  belongs_to :original_trade, class_name: 'Trade'

  delegate :base, :quote, to: :market, allow_nil: true

  def market
    @market ||= Market.find market_id
  end

  def revenue
    if side? :bid
      original_trade.total - volume_price
    else
      volume_price - original_trade.total
    end
  end

  def volume_price
    volume * price
  end

  def trade_account
    Account.find trade_account_id
  end

  def buyout_account
    Account.find buyout_account_id
  end
end

app/controllers/buyout_orders_controller.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

class BuyoutOrdersController < ApplicationController
  include SelectedMarket
  include PaginationSupport

  def index
    @q = BuyoutOrder.ransack(params[:q])
    orders = @q.result

    orders = orders.where(market_id: selected_market.id) if selected_market.present?

    orders = orders.order('created_at desc')
    render locals: { paginated_orders: paginate(orders), all_orders: orders }
  end

  def show
    redirect_to buyout_orders_path
  end
end

app/helpers/buyout_orders_helper.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

module BuyoutOrdersHelper
  STATUS_CLASSES = {
    'ignored' => 'badge badge-secondary',
    'done' => 'badge badge-success',
    'posted' => 'badge badge-warn',
    'default' => 'badge badge-info',
    'errored' => 'badge badge-danger'
  }.freeze

  def buyout_order_status(buyout_order)
    css_class = STATUS_CLASSES[buyout_order.status] || STATUS_CLASSES['default']
    content_tag :span, class: css_class do
      BuyoutOrder.human_enum_name(:status, buyout_order.status)
    end
  end
end

app/views/buyout_orders/_orders.slim
table.table.table-small.table-narrow.table-stripped.table-condensed.m-0
  thead.thead-dark
    tr
      th
      th.text-small= t '.side'
      th.text-small= t '.volume'
      th.text-small= t '.price'
      th.text-small= t '.total'
  tbody
    tr style="background-color: #{side_bg_color(buyout_order.original_trade.side)}"
      th.text-small
        = link_to trade_path(buyout_order.original_trade), title: buyout_order.original_trade.id do
          = t '.original_trade'
      td.text-small= buyout_order.original_trade.side
      td.text-small= format_money buyout_order.original_trade.amount, buyout_order.original_trade.base || '???'
      td.text-small= format_money buyout_order.original_trade.price, buyout_order.original_trade.quote || '???'
      td.text-small= format_money buyout_order.original_trade.total, buyout_order.original_trade.quote || '???'
    tr style="background-color: #{side_bg_color(buyout_order.side)}"
      th.text-small= t '.created_order'
      td.text-small= buyout_order.side
      td.text-small= format_money buyout_order.volume, buyout_order.base
      td.text-small= format_money buyout_order.price, buyout_order.quote
      td.text-small= format_money buyout_order.volume_price, buyout_order.quote
  tfoot
    tr
      th.text-small.text-right colspan=4
        = t '.revenue'
      td.text-small= format_money buyout_order.revenue, buyout_order.quote

app/views/buyout_orders/index.html.slim
.container-fluid
  h2= t '.buyout_orders'
  hr
  = render 'markets_select', selected_market: selected_market
  = render 'ransack_conditions', conditions: @q.conditions
  - if all_orders.any?
    = render 'table', scope: paginated_orders, decorator: BuyoutOrderDecorator

  = paginate paginated_orders