config/routes.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'strategies#index'
  resources :strategies, only: %i[index show]
  resources :markets, only: %i[index show]
  resources :balances, only: %i[index]
  resources :strategy_settings, only: %i[update] do
    member do
      post :start
    end
  end
  resources :upstream_markets, only: %i[index show]
  resources :upstreams, only: %i[index show]
  resources :accounts, only: %i[index show]
  resources :drainers, only: %i[index show]
  resources :trades, only: %i[index show]
  resources :buyout_orders, only: %i[index show]
end

app/controllers/balances_controller.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

class BalancesController < ApplicationController
  def index
    currencies = (Market.all.map(&:currencies).flatten +
                  Account.all.map do |a|
                    a.balances.transform_values do |v|
                      v if (v['available'].to_d + v['locked'].to_d).positive?
                    end.compact.keys
                  end.flatten).uniq
    render locals: {
      currencies: currencies,
      accounts: Account.all
    }
  end
end

app/views/balances/index.html.slim
.container-fluid
  h2= t '.balances'
  hr
  table.table.table-striped.table-hover.table-narrow.table-bordered.text-small.table-sm
    thead.thead-dark
      tr
        th
        - currencies.each do |currency|
          th.text-right.text-nowrap= currency
    tbody
      - accounts.each do |account|
        tr is='dapi-tr' data-href=url_for(account)
          td
            = link_to account, account_path(account.id)
          - currencies.each do |currency|
            - balance = account.balances.transform_keys(&:upcase)[currency]
            td.text-right.text-nowrap
              - if balance.present?
                = format_money balance['available'].to_d + balance['locked'].to_d, currency, show_currency: false
              - else
                = middot