config/routes.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'strategies#index'
  resources :strategies, only: %i[index show]
  resources :markets, only: %i[index show]
  resources :balances, only: %i[index]
  resources :strategy_settings, only: %i[update] do
    member do
      post :start
    end
  end
  resources :upstream_markets, only: %i[index show]
  resources :upstreams, only: %i[index show]
  resources :accounts, only: %i[index show]
  resources :drainers, only: %i[index show]
  resources :trades, only: %i[index show]
  resources :buyout_orders, only: %i[index show]
end

app/controllers/application_controller.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

class ApplicationController < ActionController::Base
  http_basic_authenticate_with(**Rails.application.credentials[:http_basic_auth])

  private

  def god
    @god ||= God.instance
  end
end

app/helpers/application_helper.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

module ApplicationHelper
  def active_class(css_classes, flag)
    flag ? "#{css_classes} active" : css_classes
  end

  def middot
    content_tag :div, '&middot;'.html_safe, class: 'text-muted'
  end

  def account_link(account)
    link_to "@#{account}", account_path(account.id)
  end

  def sorted_orders_by_side(orders, side)
    orders.to_a
          .filter { |o| o.side? side }
          .sort # sort_by { |o| side.downcase.to_s == 'ask' ? -o.price : o.price }
  end

  BG_SIDE_COLORS = { 'ask' => '#fee', 'bid' => '#efe' }.freeze
  def side_bg_color(side)
    BG_SIDE_COLORS[side.to_s]
  end

  def colorized_side(side)
    css_class = side.to_s == 'ask' ? 'badge badge-danger' : 'badge badge-success'
    content_tag :span, class: css_class do
      side
    end
  end

  def app_title
    'VALERA'
  end

  def logged_in?
    false
  end

  def grafana_iframe_src(resource, panel_id = nil)
    panel_id ||= Rails.application.credentials.grafana[:panel_id]
    grafana_url = Rails.application.credentials.grafana[:url] || '&refresh=5s'
    case resource
    when Strategy
      grafana_url +
        "&var-market=#{resource.market.id}&var-bot=#{resource.name}&panelId=#{panel_id}"
    when Market
      grafana_url +
        "&var-market=#{resource.id}&var-bot=All&panelId=#{panel_id}"
    else
      raise "Inknown resource #{resource}"
    end
  end

  def present_time(time)
    return middot if time.nil?

    I18n.l time, format: :default
  end

  def present_latest_order(last_orders, side, key, currency)
    return middot if last_orders.nil?

    order = last_orders.find { |o| o['side'] == side }
    return middot if order.nil?

    format_money(order[key.to_s], currency)
  end

  def process_status(pid)
    return content_tag :span, 'Не запущен', class: 'badge badge-danger' if pid.nil?

    Process.getpgid pid
    content_tag :span, 'Живой', class: 'badge badge-success', title: "pid: #{pid}"
  rescue StandardError => e
    content_tag :span, e.message, class: 'badge badge-danger'
  end

  def format_percent(value)
    return middot if value.nil?

    content_tag :span, class: 'text-monospace' do
      "#{value}%"
    end
  end

  def humanized_time_ago(time)
    if time.nil?
      t('.never')
    else
      content_tag :span, title: time do
        time_ago_in_words time, include_seconds: true
      end
    end
  end

  def settings_attribute_title(attribute)
    content_tag :span, title: attribute do
      t attribute, default: default_settings_attribute(attribute), scope: :settings_attributes
    end
  end
end

app/views/application/_buyout_brief.slim
- bo = BuyoutOrderDecorator.decorate(buyout_order)
div
  span.mr-2= bo.status
  = link_to '#'+buyout_order.id.to_s, buyout_order_path(buyout_order), target: '_blank'
= bo.ignore_message

app/views/application/_markets_select.slim
ul.nav.nav-pills.mb-3
  li.nav-item
    = link_to t('.all'), url_for(request.query_parameters.merge(market_id: nil)), class: active_class('nav-link', selected_market.nil?)
  - Market.all.each do |market|
    li.nav-item
      = link_to market.to_s, 
        url_for(request.query_parameters.merge(market_id: market.id)), class: active_class('nav-link', market == selected_market)

app/views/application/_navbar.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light.flex-column.flex-md-row.sticky-top[style="background-color: #e3f2fd;"]
  = content_tag :div, class: 'container-fluid' do
    a.navbar-brand( href=main_app.root_path title=AppVersion.to_s)
      = image_tag asset_path('logo.svg'), width: 32
      span.ml-2= app_title
    button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Navigation"]
      span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.mr-auto
        = yield
      = render 'navbar_user_dropdown'

app/views/application/_navbar_user_dropdown.slim
- if logged_in?
  ul.navbar-nav.navbar-right
    li.nav-item.dropdown
      = link_to '#', class: 'my-lg-0 py-lg-0 nav-link dropdown-toggle', data: { toggle: 'dropdown' }, id: :navbarDropdown, role: :button, 'aria-haspopup' => true, 'aria-expanded' => false do
        = gravatar_tag current_user,
          size: 32
        span.ml-2
          span= current_user.email
      .dropdown-menu.dropdown-menu-right[aria-labelledby="navbarDropdown"]
        - if current_user.superadmin? || Rails.env.development?
          = link_to t('.sidekiq_web'), Rails.application.routes.url_helpers.operator_sidekiq_web_path, class: 'dropdown-item'
          = link_to t('.operator'), Rails.application.routes.url_helpers.operator_root_path, class: 'dropdown-item'
        /= link_to t('.api'), root_api_path, class: 'dropdown-item'
        /- if !Rails.env.production? || current_super_admin.present?
          /.dropdown-divider
          /- if Rails.env.development? || Rails.env.staging?
            /= link_to 'Letter Opener', letter_opener_web_path, class: 'dropdown-item'
            /= link_to 'Mail templates preview', '/rails/mailers', class: 'dropdown-item' if Rails.env.development?
          /- if current_super_admin.present?
            /= link_to 'Super login as other user', new_super_user_path, class: 'dropdown-item'
            /= link_to 'Sidekiq', sidekiq_web_path, class: 'dropdown-item'
        /.dropdown-divider
        /= link_to t('.logout'), sessions_path, method: :delete, class: 'dropdown-item'

app/views/application/_periodical_update_page.slim
javascript:
  if(!window.reloadTimer) {
    var SECONDS = 3;
    window.reloadTimer=setTimeout(function(){
      console.log("Reload!");
      window.reloadTimer=undefined;
        Turbolinks.visit(location.toString(),{action: "advance"});
    }, SECONDS * 1000);
    document.addEventListener("turbolinks:visit",function() {clearTimeout(window.reloadTimer);window.reloadTimer=undefined;});
  }

  window.lastFocusedId = null;

  document.addEventListener("turbolinks:request-start", function () {
    const element = document.querySelector(
      ":focus"
    );

    if (element) {
      window.lastFocusedId = element.id;
    }
  });

  document.addEventListener("turbolinks:load", function () {
    if (!window.lastFocusedId) return;

    const element = document.getElementById(window.lastFocusedId);
    window.lastFocusedId = null;

    if (!element) return;

    element.focus();
  });

app/views/application/_persisted_orders.slim
- if orders.any?
  table.table.table-condensed.table-striped.table-sm
    thead.thead-light
      tr
        th.text-small ID
        th.text-small Origin Volume
        th.text-small Remaining Volume
        th.text-small Price
        th.text-small Quote volume
    tbody
      - total_volume = 0.0
      - total_price = 0.0
      - total_quote_volume = 0.0

      - orders.each do |order|
        tr
          td
            .text-small.text-monospace.text-muted= '#' + order['id'].to_s
          td.text-small= format_money(order.origin_volume, market.base)
          td.text-small= format_money(order.remaining_volume, market.base)
          td.text-small= format_money(order.price, market.quote)
          td.text-small= format_money(order.price*order.remaining_volume, market.quote)
        - total_quote_volume += order.price * order.remaining_volume
        - total_volume += order.remaining_volume
        - total_price += order.price * order.remaining_volume
    - if orders.many?
      tfoot.tfoot-light
        tr
          th.text-small colspan=2
            = t '.total_remaining'
          td.text-small.text-monospace= format_money total_volume, market.base
          td.text-small.text-monospace= format_money total_price/total_volume, market.quote
          td.text-small.text-monospace= format_money total_quote_volume, market.quote

- else
  .text-center.mt-2= middot

app/views/application/_short_balances.slim
- balances.each_pair do |currency, amounts|
  div= format_money amounts['available'].to_d + amounts['locked'].to_d, currency

app/views/application/_strategy_enabler.slim
.form-group.form-inline
  label.text-small.mr-2 for=:enabled
    = t '.target_state'
  = strategy_settings_attribute_input strategy, :target_state

app/views/application/_strategy_select.slim
ul.nav.nav-pills.mb-3
  li.nav-item
    = link_to t('.all'), url_for(request.query_parameters.merge(strategy_name: nil)), class: active_class('nav-link', selected_strategy.nil?)
  - Strategy.all.map(&:name).uniq.each do |strategy_name|
    li.nav-item
      = link_to strategy_name, 
        url_for(request.query_parameters.merge(strategy_name: strategy_name)), 
        class: active_class('nav-link', strategy_name == selected_strategy)

app/views/application/_table.slim
- if scope.empty?
  p.text-muted= t '.empty_table'
- else
  - if scope.respond_to?(:decorate)
    - scope = scope.decorate unless scope.respond_to?(:decorated?) && scope.decorated?
  - decorator ||= scope.first.is_a?(ApplicationDecorator) ? scope.first.class : scope.first.decorator_class
  - columns = decorator.table_columns unless defined?(columns) && columns.present?
  table.table.table-striped.table-hover.table-narrow data-sticky=true class=(defined?(table_classes) ? table_classes : '')
    thead.thead-dark
      tr
        - columns.each do |column|
          th class=(decorator.present? ? decorator.table_th_class(column) : '') title=column
            - title = decorator.object_class.respond_to?(:human_attribute_name) ? decorator.object_class.human_attribute_name(column) : column
            = decorator.present? && respond_to?(:sort_column) ? sort_column(column, title) : column
    - if block_given?
      thead.thead-light
        = yield
    tbody
      - scope.each do |item|
        - item_decorated = item.respond_to?(:decorated?) && item.decorated? ? item : decorator.decorate(item)
        tr is='dapi-tr' data-href=url_for(item) class=item_decorated.class.table_tr_class(item)
          - columns.each do |column|
            td class=item_decorated.class.table_td_class(column)
              = item_decorated.send column

app/views/application/_trade_brief.slim
table.table.table-small.table-narrow
  tbody
    tr
      th Side
      td= trade.side
    tr
      th Price
      td.text-right= format_money trade.price, trade.market.quote
    tr
      th Amount
      td.text-right= format_money trade.amount, trade.market.base
    tr
      th Total
      td.text-right= format_money trade.total, trade.market.quote

app/views/application/_trades_amounts.slim
table.table.table-sm
  tbody
    - amounts.each_pair do |market_id, amount|
      - market = Market.find market_id
      tr
        td.text-small= market.to_s
        td.text-small.text-nowrap
          = link_to trades_path(q: { account_id_eq: account.id, traded_at_gteq: time_ago, market_id_eq: market_id }) do
            - if market.present?
              = format_money amount, market.base
            - else
              div unknown market #{market_id}

app/views/application/_universe_enabler.slim
.form-group.form-inline
  label.text-small for=:enabled
    = t '.running'
  = strategy_settings_attribute_input strategy, :enabled

app/views/application/_universe_settings_form.slim
- attributes = strategy.settings.class.scope_attributes(scope)
.row
  - attributes.reject { |a| a.to_s.split('_').last.to_i.to_s == a.to_s.split('_').last }.each do |attribute|
    .col-md-3.form-group style='min-width: 160px'
      .md-2= render 'settings_field', strategy: strategy, attribute: attribute

- if strategy.settings.levels.positive?
  table.table.table-condensed.table-narrow
    thead.thead-light
      tr
        th Level
        - strategy.settings.leveled_attributes_unsuffixed.each do |attribute|
          th= t attribute, default: default_settings_attribute(attribute)
    tbody
      - strategy.settings.levels.times.each do |level|
        tr
          th.text-nowrap width="70px"= level.to_s
          - strategy.settings.leveled_attributes_unsuffixed.each do |attribute|
            td
              = strategy_settings_attribute_input strategy,  attribute.to_s+'_'+level.to_s