config/routes.rb
# Copyright (c) 2019 Danil Pismenny <danil@brandymint.ru>

# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'strategies#index'
  resources :strategies, only: %i[index show]
  resources :markets, only: %i[index show]
  resources :balances, only: %i[index]
  resources :strategy_settings, only: %i[update] do
    member do
      post :start
    end
  end
  resources :upstream_markets, only: %i[index show]
  resources :upstreams, only: %i[index show]
  resources :accounts, only: %i[index show]
  resources :drainers, only: %i[index show]
  resources :trades, only: %i[index show]
  resources :buyout_orders, only: %i[index show]
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title= app_title
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'https://unpkg.com/ionicons@4.2.2/dist/css/ionicons.min.css', media: 'all'

    = javascript_include_tag "https://code.jquery.com/jquery-3.3.1.min.js"
    = javascript_include_tag "//ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"

    = javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    = javascript_include_tag '//unpkg.com/@ungap/custom-elements'

    = stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'
    = javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js'

    = stylesheet_link_tag :application, media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag :application, 'data-turbolinks-track' => :reload

    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'navbar' do
      = active_link_to t('.balances'), balances_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item'
      = active_link_to t('.strategies'), strategies_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item'
      = active_link_to t('.markets'), markets_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item'
      = active_link_to t('.upstreams'), upstreams_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item'
      = active_link_to t('.upstream_markets'), upstream_markets_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item'
      = active_link_to t('.accounts'), accounts_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item'
      = active_link_to t('.drainers'), drainers_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item'
      = active_link_to t('.trades'), trades_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item'
      = active_link_to t('.buyout_orders'), buyout_orders_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item'
      = active_link_to t('.sidekiq'), sidekiq_web_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item' if defined? Sidekiq

    = yield
    = render 'footer'